services:
  contactfind-api:
    build:
      context: .
      dockerfile: src/Postech.GroupEight.ContactFind.Api/Dockerfile
    image: contactfind-api:latest
    ports:
      - "5266:5266"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  app-network:
    external: true