services:
  contactfind_api:
    build:
      context: .
      dockerfile: src/Postech.GroupEight.ContactFind.Api/Dockerfile
    container_name: contactfind_api
    ports:
      - "5266:5266"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - MONGO_CONNECTION_STRING=mongodb://fiap:fiap123456@mongodb:27017/admin
    networks:
      - techchallenge-worker-persistency_custom_network

networks:
  techchallenge-worker-persistency_custom_network:
    external: true