services:
  contactfind-api:
    build:
      context: .
      dockerfile: src/Postech.GroupEight.ContactFind.Api/Dockerfile
    image: contactfind-api:latest
    ports:
      - "5266:5266"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGO_CONNECTION_STRING=mongodb://fiap:fiap123456@mongodb:27017/admin
    networks:
      - app-network

networks:
  app-network:
    external: true