apiVersion: v1
kind: Secret
metadata:
  name: techchallenge-dotnet-contactfind-secret
type: Opaque
data:
  MONGO_CONNECTION_STRING: bW9uZ29kYjovL2ZpYXA6ZmlhcDEyMzQ1NkBzZXJ2aWNlLW1vbmdvLWRiOjI3MDE3L2FkbWlu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallenge-dotnet-contactfind
  labels:
    app: techchallenge-dotnet-contactfind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techchallenge-dotnet-contactfind
  template:
    metadata:
      labels:
        app: techchallenge-dotnet-contactfind
    spec:
      containers:
        - name: container-techchallenge-dotnet-contactfind
          image: brenojgomes/contactfind_api:4
          livenessProbe:
            httpGet:
              path: /health
              port: 5266
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 5266
            initialDelaySeconds: 20
            periodSeconds: 60
            failureThreshold: 3
          ports:
            - containerPort: 5266
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Docker"
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: techchallenge-dotnet-contactfind-secret
                  key: MONGO_CONNECTION_STRING
---
apiVersion: v1
kind: Service
metadata:
  name: contact-find-api-service
  labels:
    app: techchallenge-dotnet-contactfind
spec:
  type: NodePort
  ports:
  ports:
    - protocol: TCP
      port: 5266
      targetPort: 5266 
      nodePort: 31475
  selector:
    app: techchallenge-dotnet-contactfind
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-techchallenge-dotnet-contactfind
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: techchallenge-dotnet-contactfind
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 70

